In [19]:
import numpy as np
import math
import matplotlib.pyplot as plt

def calculo_accuracy(X, Y, w):
    #Calculando a acurácia
    correct_predictions = 0
    for i in range(len(X)):
        prediction = sigmoid(np.dot(w, X[i]))
        #print("Preveu ",prediction)
        if sinal(prediction) == Y[i]:
            correct_predictions += 1
    accuracy = correct_predictions / len(X)
    return accuracy

def calcular_erro(Y, p_chapeu):
    N = len(p_chapeu)
    erro = 0
    for n in range(N):
        erro += -(Y[n] * np.log(p_chapeu[n]) + (1 - Y[n]) * np.log(1 - p_chapeu[n]))
    return erro / N


def sigmoid(z):
    return 1 / (1 + np.exp(-z))
def sinal(z):
    return 1 if z > 0.5 else 0


def calculo_S(p_chapeu, Y, X, X_batch):
    N = len(X)
    S_aux = []
    for n in range(len(X_batch)):
        S_aux.append((p_chapeu[n] - Y[n]) * np.array([np.dot(X[l], X[n]) for l in range(N)]))
    S = np.sum(S_aux, axis=0)
    return S / N





def calcula_p_chapeu(alpha, X_batch, X):
    p_chapeu =[]
    for n in range(len(X_batch)):
        somatorio=0
        for l in range(len(X)):
            somatorio = alpha[l]*np.dot(X[l],X_batch[n])
        p_chapeu.append(sigmoid(somatorio))
    return p_chapeu      
        
def batche(X, Y, percent_to_keep):
    num_to_keep = math.ceil(len(X) * percent_to_keep)
    if num_to_keep >= len(X):
        return X.copy(), Y.copy()
    indices_to_keep = np.random.choice(len(X), num_to_keep, replace=False)
    X_batch = X[indices_to_keep]
    Y_batch = Y[indices_to_keep]
    return X_batch, Y_batch       

# Algoritmo conforme o pseudocódigo
def CLOGMGB(X, Y, alpha, eta,batch_size,epochs):
    t=0
    E=[]
    batch_size = batch_size/len(X)
    for epoca in range(epochs):
        X_batch, Y_batch = batche(X,Y,batch_size)
        p_chapeu = calcula_p_chapeu(alpha, X_batch, X)
        S = calculo_S(p_chapeu, Y, X, X_batch)
        print(S)
        alpha = alpha - eta * S
        print("Usando : ", len(X_batch)," Elementos")
    return E, np.array(alpha)
        
         
            
# Dados de entrada
X = np.array([[1, 1, 1], [1, 0, 0], [1, 1, 0], [1, 0, 1]])
Y = np.array([1, 0, 0, 0])


eta = 1
batch_size = 4
epochs = 200
alpha = np.zeros(len(X))
E, alpha = CLOGMGB(X, Y, alpha, eta, batch_size,epochs)

# Relacionando o Alpha com w til
w = np.array([0, 0, 0])
for l in range(len(alpha)):
    w = w + alpha[l]*X[l]
wr = w
print("w relacionado com alpha : ", wr)
print(calculo_accuracy(X, Y, w))
print("w Optimo ->", wr)


[0.25 0.25 0.25 0.25]
Usando :  4  Elementos
[0.05029346 0.15768208 0.11152313 0.09645242]
Usando :  4  Elementos
[-0.02258379  0.12381508  0.06072262  0.04050867]
Usando :  4  Elementos
[-0.05212411  0.11004017  0.04006026  0.01785581]
Usando :  4  Elementos
[-0.06492264  0.10406206  0.03109309  0.00804633]
Usando :  4  Elementos
[-0.07064386  0.10138761  0.02708142  0.00366233]
Usando :  4  Elementos
[-0.07323827  0.10017438  0.02526157  0.00167454]
Usando :  4  Elementos
[-0.0744225   0.09962051  0.02443076  0.00076725]
Usando :  4  Elementos
[-0.07496467  0.09936691  0.02405036  0.00035188]
Usando :  4  Elementos
[-0.07521323  0.09925064  0.02387596  0.00016145]
Usando :  4  Elementos
[-7.53272566e-02  9.91973025e-02  2.37959538e-02  7.40921534e-05]
Usando :  4  Elementos
[-7.53795817e-02  9.91728262e-02  2.37592393e-02  3.40051956e-05]
Usando :  4  Elementos
[-7.54035959e-02  9.91615930e-02  2.37423894e-02  1.56076204e-05]
Usando :  4  Elementos
[-7.54146177e-02  9.91564372e-02  2